### ISSUE TITLE
backends and multithreading

### ISSUE THREAD

**Issue by aestrivex** [nipy/PySurfer#106]
The current pysurfer code to use traitsui involves strange hacks to make the GUI busy for a short time while X renders the mayavi window but also without causing the GUI to enter an event loop and block. This section of code is very difficult to understand and maintain. A much more natural solution would be to use multithreading and explicit management of locking constructs to ensure that all of the events happen at the correct time.

The problem with this code is mainly with traitsui, which is an interactive GUI but which pysurfer is trying to use as a noninteractive GUI. Traitsui doesn't expose an API to usefully allow for precise timing of the GUI to be controlled in a multithreaded environment. In order to get the correct behavior without generating potential race conditions (which I think is what is happening now, only it is a race condition that is extremely unlikely to ever lose the race), I don't think embedding mayavi in traitsui will work.

I don't know any visualization libraries other than mayavi but I have been working on some simple tests to operate on VTK windows can be managed and display at the correct times in GUI code that does not involve traitsui -- I have proof of concept tests that suggest this should work with wxpython and tk (but it did not work at all with pyqt). As wxpython is not included in anaconda by default (and nothing about the GUI layout in pysurfer is particularly complex), tk is probably the better choice.

I'm of the opinion that to fix the current problems with traitsui, pysurfer should move in this direction (and I anticipate doing the majority of the work). This won't per se help eliminate dependencies on python 2.7 more quickly, but it will provide something more stable and maintainable so that pysurfer might later move to multiple backends as has been discussed before.

**Comment by wmvanvliet** [comment]
@Eric89GXL any progress on the move to vispy? :)

**Comment by Eric89GXL** [comment]
Heh, not much so far

**Comment by mwaskom** [comment]
Meanwhile, looks like some progress on getting mayavi running on python 3: https://github.com/enthought/mayavi/pull/250

**Comment by wmvanvliet** [comment]
that's promising!

**Comment by choldgraf** [comment]
Hey folks - diving in this conversation with another potential option here. I've been working on the `plotly` trisurf libraries for the last week, and got the plotting time for an `fsaverage` hemisphere down to about 10 seconds. It's still a bit slow IMO, but probably there are lots of improvements to be made as well.

Plotly uses WebGL as a backend, so the plots are rendered in the browser but they're pretty smooth and much more stable than Mayavi. E.g., here's a quick package/demo I put together as a proof of concept:

https://github.com/choldgraf/ecogtools/blob/master/examples/3d_plots.ipynb

![image](https://cloud.githubusercontent.com/assets/1839645/15657626/65ff893c-2667-11e6-9bc0-d2779c576fc9.png)

Perhaps this could be integrated into pysurfer? The pros and cons as I see it would be:

Pros
* Browser rendering
* More stable / fully featured than Mayavi
* Theoretically more extensible if people want to dive into javascript ;)
* Works (more or less) right now

Cons
* Potentially *only* browser rendering
* Still a bit slow (10s for `fsaverage` hemisphere)
* Disconnection between the JS kernel and the python kernel (e.g., right now I'm not sure how to interactively pass data between them)
* Would introduce another dependency (on `plotly`)

(also note, right now I *think* there's a memory leak on the javascript side of things in plotly, so if you plot and re-plot a brain a bunch of times it will slow things down unless you restart python).

LMKWYT.

**Comment by choldgraf** [comment]
Also here's an example of what the interactive output would look like:

https://www.dropbox.com/s/o4j02go41lx0gqm/brainz.html?dl=0

All the data is packaged in the HTML (it's what plotly outputs when you save to html) so it should be able to fully recreate the plot but is also big-ish (at ~36mb)

**Comment by mwaskom** [comment]
With Mayavi on Python 3, I'm not sure there's a compelling reason to completely rewrite pysurfer for a different rendering engine, and on a quick look it seems there's so many differences between mayavi and plotly that they wouldn't really work as modular backend options.

**Comment by Eric89GXL** [comment]
I pretty often run into problems with Mayavi, even on python 2.7. Alex and
I just taught a course with two dozen people, and I would say a handful (if
any?) had a working Mayavi setup :( Personally I frequently experience
breakages of various types (segfaults, X opcode errors) on 2.7. The 3.5
setup I recently got working I couldn't use to build the MNE python docs.
Even though that's still experimental, my 2.7 experiences make me wary of
relying on Mayavi.

That said, I would like to see output closer to that of Mayavi if possible,
at the very least with multiple views at the same time, before adding
another backend. Otherwise I have no problem with multiple backends if we
document that others are experimental and do not give exactly equivalent
output visually.

But if this seems like too ugly a solution, we could start building some
alternative package.

**Comment by mwaskom** [comment]
I've had pretty good luck with mayavi recently, but i guess things just work on a mac ;)

**Comment by choldgraf** [comment]
Ya I think that's a reasonable point. In my experience Mayavi had been
pretty unstable (eg it crashes on our cluster once out of every 10 plots
I'd say) , and doesn't have more "standard" plot types like scatterplots,
which is why I've been looking for another option, but if it'd be a big
backend change and folks are happy w Mayavi then perhaps not worth it...

With Mayavi on Python 3, I'm not sure there's a compelling reason to
completely rewrite pysurfer for a different rendering engine, and on a
quick look it seems there's so many differences between mayavi and plotly
that they wouldn't really work as modular backend options.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nipy/PySurfer/issues/106#issuecomment-222550891>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABwSHeQD3ZmPJhPN2DkYtqCKkaf81GXoks5qG0iJgaJpZM4B5NkJ>
.

**Comment by mwaskom** [comment]
> (also note, right now I think there's a memory leak on the javascript side of things in plotly, so if you plot and re-plot a brain a bunch of times it will slow things down unless you restart python).

at least this would maintain backwards compatibility with our current memory leak!

**Comment by choldgraf** [comment]
Haha, I am happy to introduce new bugs as well ;-)

**Comment by mwaskom** [comment]
Curious what you're looking for in terms of a scatterplot? Mayavi has a 3d scatterplot function that is the basis for `Brain.add_foci`.

**Comment by choldgraf** [comment]
I'm coming from the world of ecog, where it's common to represent electrode
locations as circles on top of a brain. Some folks just project the
activity onto the surface, but it's more common to just do a 3d
scatterplot. The orbs in Mayavi are ok, but IMO they don't have a journal
quality feel to them. The closest I could get with Mayavi was to render
discs that would reorient themselves to the camera as you moved it around,
but it was pretty hacky, so I started looking into other packages.

Heres an example of a matlab package that does something like this :

https://github.com/edden-gerber/ecog_fmri_visualization_matlab.git

Sent from my phone, apologies for the curtness and type-os

Curious what you're looking for in terms of a scatterplot? Mayavi has a 3d
scatterplot function that is the basis for Brain.add_foci.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nipy/PySurfer/issues/106#issuecomment-222558451>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABwSHdhlZPLvdz3MQL5OxqVTgKoTpZ0Aks5qG1twgaJpZM4B5NkJ>
.

**Comment by choldgraf** [comment]
So do folks think it's not worth implementing any kind of backend change then? If so then I'll just keep my own set of ecog surface plotting functions that use plotly under the hood.

btw, I meant to link to this image, not the git repo:
![image](https://cloud.githubusercontent.com/assets/1839645/15911487/eec6d8e6-2d84-11e6-8fca-deccdeed4447.png)

**Comment by Eric89GXL** [comment]
I'm pretty skeptical that `plotly` can get sufficient performance to replace enough of PySurfer's functionality to warrant a backend. Think for example of having lat/med split view of left/right hemisphere, with an STC overlay from MNE-Python. That's effectively 8 meshes that need to be shown, and it was already pretty slow for me with one.

Have you gotten good performance out of it? Can you show an STC on four views simultaneously in some reasonable way? I'd try that first, and if you can get it working, it might be worth considering as a backend.

Here is some boilerplate MNE/nibabel code to get you started with per-vertex (on the high-resolution `fsaverage` mesh) `curv` values (that give you the light/dark colors) and STC values that need to be colormapped:

```Python
data_path = mne.datasets.sample.data_path()
subjects_dir = data_path + '/subjects'
subj_dir = subjects_dir + '/sample/surf/'
stc = mne.read_source_estimate(data_path + '/MEG/sample/sample_audvis-meg-eeg')
stc.crop(0.09, 0.09)
stc = stc.morph('sample', grade=None, smooth=10, subjects_dir=subjects_dir,
                subject_from='sample')
hemi_data = dict(lh=stc.data[:len(stc.vertices[0]), 0],
                 rh=stc.data[len(stc.vertices[0]):, 0])
for hemi in ['lh', 'rh']:
    data = hemi_data[hemi]
    surf = subj_dir + '%s.inflated' % hemi
    curv = subj_dir + '%s.curv' % hemi
    rr, tris = nibabel.freesurfer.read_geometry(surf)
    assert len(data) == len(rr)
    curv = nibabel.freesurfer.read_morph_data(curv)
    curv = (curv > 0).astype(float)
    for view in ['lat', 'med']:
        ...
```

**Comment by choldgraf** [comment]
Ah thanks, that's useful. If I have some time I'll see if I can get the time down.

Plotly's performance definitely needs improving, and I think your skepticism is reasonable since AFAIK they aren't expecting their users to have many thousands of datapoints, but you never know, they were pretty helpful in just getting to this level of functionality. Probably best to just keep an eye on it over the months and see how it evolves.

I am in no way attached to using plotly for a backend, I've just been pretty unhappy with Mayavi, and after searching quite a bit this is the only other alternative that I've found in python (assuming that vispy is slowed down significantly :) )

**Comment by choldgraf** [comment]
btw, how long would you say it takes to make the above plot? In my experience the data creation step takes maybe 1-3 seconds for an fsaverage hemisphere. Then the final WebGL plot takes another couple of seconds...not sure how that scales w/ more data though.

**Comment by mwaskom** [comment]
> So do folks think it's not worth implementing any kind of backend change then? 

I generally tend to take a conservative opinion about large changes, especially initiatives like "rewrite the whole backend!". In the past I've expressed some interest in a javascript-based backend that would let PySurfer live inside a Jupyter notebook, and I still think this could be a very interesting app. I am worried that adding multiple backends to PySurfer, which was never the original plan, would be a superadditive interaction in terms of maintenance demands. And lately I've figured out some aspects of using Mayavi for more interactive work (and have a lot of code that touches mayavi directly for some figure tweaks that aren't exposed through PySurfer) and (maybe selfishly) wouldn't want to totally abandon Mayavi.

I guess my other thought is that there are a number of things that would be great to see in a Python-based surface viewer that would require a lot of work to incorporate into PySurfer (like a data system that is less closely tied to Freesurfer) and so my thought has always been that it might be easier to write a new package from scratch with some more prospection about issues that weren't on my radar when I first hacked together v0.1 of PySurfer 5 years ago.

Of course, that's always easier said than done too...

**Comment by choldgraf** [comment]
I think that's fair. Sounds like the best bet is to hold off on any big changes until it's really obvious that there's a better solution than Mayavi. I don't think that plotly is at the point yet where it's worth betting the farm on it, but perhaps it (or another solution) will improve in the near future. For now, I will build up my own libraries that use plotly here:

https://github.com/choldgraf/ecogtools/blob/master/ecogtools/viz3d.py

I'll see how much viz flexibility and performance I can get out of it for plotting brains, and if in the future it seems like it's worth either adding as a backend here, or contributing to some new package, then I can help out then.

Another project worth keeping an eye on is the [pycortex](https://github.com/gallantlab/pycortex) package (currently run out of the gallant lab at Berkeley). It has a lot of beautiful plotting functionality, but is a bit rough around the edges right now, and is a lot bulkier than pysurfer.

**Comment by larsoner** [comment]
I think we've settled on "we're stuck" on this for now, so I'll close. But we can reopen if new ideas come to light.
