### ISSUE TITLE
ENH? silent errors on saving montage

### ISSUE THREAD

**Issue by dengemann** [nipy/PySurfer#146]
I'm a bit surprised about this line:

https://github.com/nipy/PySurfer/blob/master/surfer/viz.py#L152

It recently caused a lot trouble as images where not saved and subsequent report tools read in wrong temporary files from previous analyses.
Why do we need a try/except block here?
It is very difficult to learn something about the underlying issue if errors are silenced.

**Comment by Eric89GXL** [comment]
I agree it's not a good idea to silence the warning, +1 for removing the `try`. I think if people want to have such uncertain behavior, they can do a `try` themselves. I can see why it might have been done orginally because an array is passed as the `return`, but users can still get the data with `filename=None` and *then* try saving it (with a `try` clause) if they want.

**Comment by mwaskom** [comment]
> +1 for removing the `try`

+1

**Comment by agramfort** [comment]
+1
