### ISSUE TITLE
visualizing head model in pysurfer

### ISSUE THREAD

**Issue by EhsanTadayon** [nipy/PySurfer#230]
Hi guys, 

Is there any way to visualize head models created from MNE with pysurfer?

**Comment by larsoner** [comment]
Like this?

https://martinos.org/mne/dev/auto_tutorials/plot_source_alignment.html#sphx-glr-auto-tutorials-plot-source-alignment-py

**Comment by EhsanTadayon** [comment]
Hi, 

Thanks. Yes, exactly. But, I'd like to use pysurfer rather than MNE functions. I have several electrode positions in MRI coordinate space and like to visualize it on the skull surface created from MNE.

**Comment by larsoner** [comment]
You can set `coord_frame='mri'` in [plot_alignment](https://martinos.org/mne/dev/generated/mne.viz.plot_alignment.html#mne.viz.plot_alignment) and it will be the same coordinate space that PySurfer uses, except (IIRC) it's in `m` units rather than `mm`. So set `coord_frame='mri'` and divide your locations by `1000.` and you should be good to go.

PySurfer does not provide functionality to visualize the BEM surfaces, so forcing PySurfer to do what you want will be harder than getting MNE to do it.

**Comment by EhsanTadayon** [comment]
Thanks. I appreciate it. 
So, I think I go with the MNE then. By any chance, do you know if there is an easy way to project the electrode coordinates in MRI space onto skull using MNE?

**Comment by larsoner** [comment]
You can do this with EEG electrodes, yes. You can use the eeg_sensors kwarg
to do it. Let's move further discussion over to MNE, though, to relieve
other PySurfer devs.

>
